---
version: "3.8"
services:
  movies:
    image:  ram0987/moviespay:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: ram0987/trainpay:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image:  ram0987/dthpay:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image:  ram0987/rechargepay:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
